"use client";

import { useEffect, useRef, useState } from "react";
import type { InspectionView, SetupReadiness, LaunchRequest } from "../generated/contracts";
import { fetchReadiness, inspectFolder, launchReview, reviewCommand } from "../lib/setup-data";
import { runDestination } from "../lib/run-metadata";
import { Conditions } from "./Conditions";
import { CapabilityTable } from "./CapabilityTable";
import { Command, ReviewGuide } from "./Workbench";
import styles from "./SetupPanel.module.css";

export function SetupPanel(){
  const [families,setFamilies]=useState<NonNullable<LaunchRequest["families"]>>(["authorization"]);const [limit,setLimit]=useState(5);const [route,setRoute]=useState("");
  const [folder,setFolder]=useState("");const [authorized,setAuthorized]=useState(false);const [busy,setBusy]=useState(false);const [message,setMessage]=useState("");
  const [readiness,setReadiness]=useState<SetupReadiness|null>(null);const [inspection,setInspection]=useState<InspectionView|null>(null);const [inspectedFolder,setInspectedFolder]=useState("");
  const active=useRef<AbortController|null>(null);useEffect(()=>()=>active.current?.abort(),[]);
  async function check(mode:"setup"|"inspect"){
    if(busy)return;const controller=new AbortController();active.current=controller;const timer=setTimeout(()=>controller.abort(),90000);setBusy(true);setMessage(mode==="setup"?"Checking local prerequisites and current memory…":"Reading source and building a frozen overview…");
    try{if(mode==="setup"){const p=await fetchReadiness(controller.signal);if(!controller.signal.aborted){setReadiness(p);setMessage("Readiness checked. No model or download started.");}}else{const value=folder.trim();const p=await inspectFolder(value,authorized,controller.signal);if(!controller.signal.aborted){setInspection(p);setInspectedFolder(value);setMessage("Source inspection complete. No model or target code ran.");}}}
    catch(error){if(!controller.signal.aborted)setMessage(error instanceof Error?error.message:"The check could not complete.");else setMessage("The browser wait ended. The source check may still be finishing; read the terminal before retrying.");}
    finally{clearTimeout(timer);active.current=null;setBusy(false);}
  }
  async function launch(){
    if(busy||!inspection?.inspection_id||!authorized||folder.trim()!==inspectedFolder)return;
    const controller=new AbortController();active.current=controller;const timer=setTimeout(()=>controller.abort(),90000);setBusy(true);setMessage("Checking inspected source and local prerequisites before starting the review…");
    try{const run=await launchReview(inspection,{inspection_id:inspection.inspection_id,authorized:true,families,limit,routes:route.trim()?[route.trim()]:[],resources:[]},controller.signal);if(!controller.signal.aborted)window.location.assign(runDestination("/review/",run.id));}
    catch(error){setMessage(controller.signal.aborted?"The browser wait ended. Open Runs and check the terminal before retrying; a review may have started.":error instanceof Error?error.message:"Review could not start. Check readiness and inspect again.");}
    finally{clearTimeout(timer);active.current=null;setBusy(false);}
  }
  return <div id="setup" className={styles.setup}><section aria-labelledby="open-project"><h2 id="open-project">Open a local project</h2><p>Inspect a folder before investigating. Plumb reads supported source, follows static code relationships and saves a frozen snapshot.</p>
    <form className={styles.form} onSubmit={e=>{e.preventDefault();void check("inspect");}}><label>Absolute project folder<input value={folder} onChange={e=>setFolder(e.target.value)} required maxLength={4096} autoComplete="off" spellCheck={false} placeholder="D:\Projects\my-app" /></label>
      <label className={styles.authorization}><input type="checkbox" checked={authorized} onChange={e=>setAuthorized(e.target.checked)} required /><span>I own this code or am authorized to test it.</span></label><button type="submit" aria-disabled={busy}>Inspect source</button></form>
  </section><p className={styles.message} role="status">{message}</p><section className={styles.section} aria-labelledby="ready-title"><h2 id="ready-title">Local readiness</h2><p>Check verified assets, the review profile for this computer and current memory. This starts no model and installs nothing.</p><button className={styles.control} aria-disabled={busy} onClick={()=>void check("setup")}>Check readiness</button>{readiness&&<ReadinessView value={readiness} />}</section>
  {inspection&&<section className={styles.section} aria-labelledby="inspection-title"><h2 id="inspection-title">Inspected source</h2><InspectionSummary value={inspection} /><h3>Run a local review</h3><p>The review checks this inspected snapshot against the current folder, then repeats profile, asset and memory checks. Remaining work pauses at a saved checkpoint.</p><div className={styles.form}><fieldset><legend>Investigation families</legend>{(["authorization","injection","path_traversal","nextjs_exposure"] as const).map(f=><label key={f} className={styles.authorization}><input type="checkbox" checked={families.includes(f)} onChange={e=>setFamilies(previous=>e.target.checked?[...previous,f]:previous.filter(v=>v!==f))} /><span>{f.replaceAll("_"," ")}</span></label>)}</fieldset><label>Questions before pausing<input type="number" min={1} max={20} value={limit} onChange={e=>setLimit(Number(e.target.value))} /></label><details><summary>Narrow to an exact discovered route</summary><label>Route (optional)<input value={route} maxLength={256} onChange={e=>setRoute(e.target.value)} placeholder="/orders/{order_id}/invoice" /></label><p>Leave empty to include the selected families throughout supported source.</p></details><button disabled={busy||!authorized||folder.trim()!==inspectedFolder||!inspection.inspection_id||!families.length} onClick={()=>void launch()}>Run review</button></div>{folder.trim()!==inspectedFolder&&<p>The folder field changed. Inspect it again before starting.</p>}<details className={styles.section}><summary>Terminal alternative</summary><Command>{reviewCommand(inspectedFolder)}</Command><p>The terminal default is authorization. Repeat <code>--family</code> flags to select other families.</p></details><a className={styles.control} href="/runs/">Open saved run history</a></section>}
  <details className={styles.section}><summary>Setup, model installation and runtime options</summary><p>Source inspection requires Plumb's trusted helper. Review also needs verified local model/runtime assets. Preview the pinned sizes before installing.</p><Command>{"uv run plumb setup"}</Command><p>If installation is needed, use the preview's explicit install command. Downloads over 500 MB require your approval. Normal source use needs no Windows Sandbox or administrator changes.</p><p>Only the bundled hash-pinned Tandir lab currently has a tested runtime runner. General target execution remains unavailable until isolation passes its acceptance checks.</p><ReviewGuide /></details></div>;
}
const gb=(value:number|null)=>value===null?"Unknown":`${(value/1_000_000_000).toFixed(2)} GB`;
export function ReadinessView({value:p}:{value:SetupReadiness}){return <div className={styles.section}><h3>{p.ready?"Local review prerequisites ready":"Review needs attention"}</h3><p>Source inspection: {p.inspect_ready?"ready":"setup required"}. Checked {new Date(p.checked_at).toISOString().slice(0,19).replace("T"," ")} UTC.</p><dl className={styles.facts}><div><dt>Review profile</dt><dd>{p.profile_id} · {p.measured_host?"runs on this computer":"not available on this computer"}</dd></div><div><dt>Available / required RAM</dt><dd>{gb(p.available_ram_bytes)} / {gb(p.required_ram_bytes)}</dd></div>{p.required_vram_bytes>0&&<div><dt>Available / required dedicated VRAM</dt><dd>{gb(p.available_vram_bytes)} / {gb(p.required_vram_bytes)}</dd></div>}<div><dt>Local model</dt><dd>{p.model_id} · {gb(p.model_size_bytes)} · {p.model_verified?"verified":"missing or unverified"}</dd></div><div><dt>Pinned runtime</dt><dd>{p.runtime_verified?"verified":"missing or unverified"}</dd></div><div><dt>Missing pinned downloads</dt><dd>{gb(p.missing_download_bytes)}{p.requires_large_download_approval?" · approval required":""}</dd></div></dl><CapabilityTable value={p.capabilities} /><Conditions conditions={p.conditions} /><details><summary>Readiness limits</summary><ul>{p.limitations.map((text,i)=><li key={i}>{text}</li>)}</ul></details></div>;}
export function InspectionSummary({value:p}:{value:InspectionView}){return <div><h3>{p.name}</h3><p>{p.included_files} included files; {p.excluded_files} excluded paths or directories; {p.entries_total} discovered entry points; {p.unresolved_links} unresolved source links.</p><p>Languages: {Object.entries(p.languages).map(([k,v])=>`${k}: ${v}`).join("; ")||"none recognized"}. Framework entries: {Object.entries(p.frameworks).map(([k,v])=>`${k}: ${v}`).join("; ")||"none discovered"}.</p><p className={styles.meta}>Snapshot <code>{p.snapshot_id}</code>. Source inventory is not a security verdict.</p><CapabilityTable value={p.capabilities} /><Conditions conditions={p.conditions} /><details><summary>Discovered entry points and scope</summary>{p.entries.length?<ul>{p.entries.map(e=><li key={e.id}><strong>{e.method||e.kind} {e.route||""}</strong><p><code>{e.span.path}:{e.span.start_line}–{e.span.end_line}</code></p></li>)}</ul>:<p>No supported entry points were discovered; unreviewed code remains unknown.</p>}<p>Showing {p.entries.length} of {p.entries_total} entries. The saved application map retains all entries.</p><ul>{Object.entries(p.exclusion_reasons).map(([kind,count])=><li key={kind}>{kind.replaceAll("_"," ")}: {count} excluded paths or directories</li>)}</ul><ul>{p.limitations.map((text,i)=><li key={i}>{text}</li>)}</ul></details></div>;}
